package api

var scopes = [22]string{
	"openid",
	"conve:commands",
	"conve:climatization_start_stop",
	"conve:command_accessibility",
	"conve:diagnostics_engine_status",
	"conve:diagnostics_workshop",
	"conve:brake_status",
	"conve:windows_status",
	"conve:doors_status",
	"conve:lock_status",
	"conve:lock",
	"conve:unlock",
	"conve:engine_status",
	"conve:engine_start_stop",
	"conve:fuel_status",
	"conve:battery_charge_level",
	"conve:honk_flash",
	"conve:odometer_status",
	"conve:trip_statistics",
	"conve:tyre_status",
	"conve:vehicle_relation",
	"conve:warnings",
}
